CREATE TABLE booking_seats
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id       BIGINT                                  NOT NULL,
    seat_row         INTEGER                                 NOT NULL,
    seat_number      INTEGER                                 NOT NULL,
    price_at_booking DECIMAL                                 NOT NULL,
    CONSTRAINT pk_booking_seats PRIMARY KEY (id)
);

CREATE TABLE bookings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    session_id     BIGINT                                  NOT NULL,
    total_amount   DECIMAL                                 NOT NULL,
    booking_status VARCHAR(255)                            NOT NULL,
    payment_status VARCHAR(255),
    confirmed_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE halls
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    rows            INTEGER                                 NOT NULL,
    seats_per_row   INTEGER                                 NOT NULL,
    schema_metadata JSONB,
    CONSTRAINT pk_halls PRIMARY KEY (id)
);

CREATE TABLE movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    genre        VARCHAR(255),
    duration     INTEGER,
    age_rating   VARCHAR(255),
    poster_url   VARCHAR(255),
    release_date date,
    is_active    BOOLEAN,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE seat_holds
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id  BIGINT,
    user_id     BIGINT,
    seat_row    INTEGER,
    seat_number INTEGER,
    expires_at  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    CONSTRAINT pk_seat_holds PRIMARY KEY (id)
);

CREATE TABLE sessions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movies_id      BIGINT                                  NOT NULL,
    hall_id        BIGINT                                  NOT NULL,
    start_datetime TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_datetime   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE TABLE ticket_prices
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id     BIGINT                                  NOT NULL,
    amount         DECIMAL                                 NOT NULL,
    currency       VARCHAR(255)                            NOT NULL,
    pricing_source VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_ticket_prices PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE ticket_prices
    ADD CONSTRAINT uc_ticket_prices_session UNIQUE (session_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_SESSION FOREIGN KEY (session_id) REFERENCES sessions (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE booking_seats
    ADD CONSTRAINT FK_BOOKING_SEATS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE seat_holds
    ADD CONSTRAINT FK_SEAT_HOLDS_ON_SESSION FOREIGN KEY (session_id) REFERENCES sessions (id);

ALTER TABLE seat_holds
    ADD CONSTRAINT FK_SEAT_HOLDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_HALL FOREIGN KEY (hall_id) REFERENCES halls (id);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_MOVIES FOREIGN KEY (movies_id) REFERENCES movies (id);

ALTER TABLE ticket_prices
    ADD CONSTRAINT FK_TICKET_PRICES_ON_SESSION FOREIGN KEY (session_id) REFERENCES sessions (id);